### ISSUE TITLE
Non operative  JDK 10  

### ISSUE THREAD

**Issue by markh2016** [mpue/blackboard#25]
Will you be making the corrective adjustments in line with the new JDK ?

**Comment by mpue** [comment]
Probably not, since this project is discontinued. I keep it online for the public, because there are many requests for that.

**Comment by markh2016** [comment]
That's a bloody good program you've written I managed to get this all up
and running eventually but had to use jdk8 instead of nine I still use it
You should continue with this I was very impressed with this

**Comment by mjg14** [comment]
Just in case someone else comes here looking for a solution, this is what worked for me on a Windows 10 machine: 

- Download and install a working version of the Java 7 JRE. 
- Modify Win_Start.bat in the BlackBoard folder to use the Java 7 java.exe, e.g. (in my case); 
> "C:\Program Files\Java\jre7\bin\java" -jar BlackBoard.jar
- Use Win_Start.bat rather than BlackBoard.exe to start BlackBoard.

**Comment by HiranChaudhuri** [comment]
I successfully got it running on OpenJDK 17. Hope my PRs get merged, then up to date builds could be provided automatically by Github. This is indeed a really good application. I am impressed.

**Comment by klauweg** [comment]
I can't get it running on OpenJDK17. But i can't see any related PRs either.

**Comment by HiranChaudhuri** [comment]
Since I saw this repo is more in archived state I removed my fork. That's likely where the PRs vanished.

**Comment by klauweg** [comment]
Ok, i see. It's really a pitty that this project isn't maintained any more.
But at least i found another fork which makes blackboard useable again with OpenJDK17: 
  https://github.com/oflebbe/blackboard

**Comment by Andy79881** [comment]
I got it not running either in Linux Mint with OpenJDK21. Installation procedure itself was successful. Starting the app I get the splash screen but without loading modules - so it is stucked at this stage. The fork does not work either. Any hints? 

Feb. 02, 2026 9:02:46 PM org.pmedv.blackboard.app.BlackBoard main
INFORMATION: Initalizing application
Feb. 02, 2026 9:02:46 PM org.pmedv.core.app.AbstractApplication <init>
INFORMATION: Working directory /home/nessi/Downloads/blackboard/.
Feb. 02, 2026 9:02:46 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFORMATION: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@63e31ee: startup date [Mon Feb 02 21:02:46 CET 2026]; root of context hierarchy
Feb. 02, 2026 9:02:46 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFORMATION: Loading XML bean definitions from class path resource [applicationContext.xml]
Feb. 02, 2026 9:02:47 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFORMATION: Loading XML bean definitions from class path resource [commands.xml]
Feb. 02, 2026 9:02:48 PM org.springframework.context.support.AbstractApplicationContext refresh
WARNUNG: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logPane' defined in class path resource [applicationContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.pmedv.core.components.LogPane]: No default constructor found; nested exception is java.lang.NoClassDefFoundError: com/jgoodies/looks/plastic/PlasticTheme
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logPane' defined in class path resource [applicationContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.pmedv.core.components.LogPane]: No default constructor found; nested exception is java.lang.NoClassDefFoundError: com/jgoodies/looks/plastic/PlasticTheme
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1232)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1131)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
	at org.pmedv.core.app.AbstractApplication.<init>(AbstractApplication.java:133)
	at org.pmedv.blackboard.app.BlackBoard.<init>(BlackBoard.java:51)
	at org.pmedv.blackboard.app.BlackBoard.main(BlackBoard.java:96)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.pmedv.core.components.LogPane]: No default constructor found; nested exception is java.lang.NoClassDefFoundError: com/jgoodies/looks/plastic/PlasticTheme
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1224)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: com/jgoodies/looks/plastic/PlasticTheme
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3551)
	at java.base/java.lang.Class.getConstructor0(Class.java:3756)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2932)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78)
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.jgoodies.looks.plastic.PlasticTheme
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 21 more
